/* tslint:disable */
/* eslint-disable */
/**
 * MUStrokeTriageApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SubjectModel
 */
export interface SubjectModel {

    /**
     * @type {string}
     * @memberof SubjectModel
     */
    subjectId?: string | null;

    /**
     * @type {string}
     * @memberof SubjectModel
     */
    phoneNumber?: string | null;

    /**
     * @type {Date}
     * @memberof SubjectModel
     */
    onsetTime?: Date;

    /**
     * @type {Date}
     * @memberof SubjectModel
     */
    lastSeenNormalTime?: Date;

    /**
     * @type {string}
     * @memberof SubjectModel
     */
    firstName?: string | null;

    /**
     * @type {string}
     * @memberof SubjectModel
     */
    lastName?: string | null;

    /**
     * @type {Date}
     * @memberof SubjectModel
     */
    createdDate?: Date;

    /**
     * @type {Date}
     * @memberof SubjectModel
     */
    modifiedDate?: Date;

    /**
     * @type {string}
     * @memberof SubjectModel
     */
    createdBy?: string | null;

    /**
     * @type {string}
     * @memberof SubjectModel
     */
    modifiedBy?: string | null;

    /**
     * @type {number}
     * @memberof SubjectModel
     */
    stateCode?: number;
}
