/* tslint:disable */
/* eslint-disable */
/**
 * MUStrokeTriageApp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Todo
 */
export interface Todo {

    /**
     * @type {number}
     * @memberof Todo
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Todo
     */
    title?: string | null;

    /**
     * @type {string}
     * @memberof Todo
     */
    dueBy?: string | null;

    /**
     * @type {boolean}
     * @memberof Todo
     */
    isComplete?: boolean;
}
