// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MUStrokeTriageApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250219184812_AddSubjectModel")]
    partial class AddSubjectModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SubjectModel", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Subject_ID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_By");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Created_Date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Last_Name");

                    b.Property<DateTime>("LastSeenNormalTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Last_Seen_Normal_Time");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Modified_By");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Modified_Date");

                    b.Property<DateTime>("OnsetTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("Onset_Time");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone_Number");

                    b.Property<int>("StateCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("State_Code");

                    b.HasKey("SubjectId");

                    b.ToTable("SubjectInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
